# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Setup common testing tools
description: Install bats and python-yq
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: '20'
    - run: sudo npm install -g bats@${BATS_VERSION}
      shell: bash
      env:
        BATS_VERSION: '1.11.0'
    - run: bats -v
      shell: bash
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.12'
    - run: pip install yq
      shell: bash
permissions:
  contents: read
