{{- if and (eq (.Values.injector.enabled | toString) "true" ) (eq (.Values.global.enabled | toString) "true") }}
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
apiVersion: admissionregistration.k8s.io/v1
{{- else }}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "vault.fullname" . }}-agent-injector-cfg
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-agent-injector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- template "injector.webhookAnnotations" . }}
webhooks:
  - name: vault.hashicorp.com
    failurePolicy: {{ .Values.injector.webhook.failurePolicy }}
    matchPolicy: {{ .Values.injector.webhook.matchPolicy }}
    sideEffects: None
    timeoutSeconds: {{ .Values.injector.webhook.timeoutSeconds }}
    admissionReviewVersions: {{ .Values.injector.webhook.admissionReviewVersions }}
    clientConfig:
      service:
        name: {{ template "vault.fullname" . }}-agent-injector-svc
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      caBundle: {{ .Values.injector.certs.caBundle | quote }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
{{- if .Values.injector.webhook.namespaceSelector }}
    namespaceSelector:
{{ toYaml .Values.injector.webhook.namespaceSelector | indent 6}}
{{ end }}
{{- if .Values.injector.webhook.objectSelector }}
    objectSelector:
{{ toYaml .Values.injector.webhook.objectSelector | indent 6}}
{{ end }}
{{ end }}
