{{- if and (eq (.Values.injector.enabled | toString) "true" ) (and (eq (.Values.global.enabled | toString) "true") (eq (.Values.injector.pdb.create | toString) "true") ) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: vault-agent-injector
spec:
  {{- if .Values.injector.pdb.minAvailable }}
  minAvailable: {{ .Values.injector.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.injector.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.injector.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vault.name" . }}-agent-injector
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      component: webhook
{{- end}}
