{{- if and (eq (.Values.injector.enabled | toString) "true" ) (eq (.Values.global.enabled | toString) "true") (eq (.Values.injector.serviceAccount.create | toString) "true")}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vault.injector.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-agent-injector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{ template "vault.injector.serviceAccount.annotations" . }}
{{ end }}
