{{- if .Values.server.logrotate}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vault.fullname" . }}-logrotate-config
  namespace: {{ .Release.Namespace }}
data:
  logrotate.conf: |
    /vault/audit/audit.log {
        rotate 1
        copytruncate
        size 5M
        missingok
        compress
        postrotate
            pkill -HUP -f "vault server"
            echo  "`date`: Audit log rotated  -  SIGHUP exit code is $?" > /vault/audit/last-rotate-status
        endscript
    }
{{ end }}