{{ template "vault.mode" . }}
{{ if .Values.telemetry.prometheusOperator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- include "prometheusOperator.selectors" .Values.telemetry.prometheusOperator.serviceMonitor | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "vault.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if eq .mode "ha" }}
      vault-active: "true"
      {{- else }}
      vault-internal: "true"
      {{- end }}
  endpoints:
  - port: {{ include "vault.scheme" . }}
    interval: {{ .Values.telemetry.prometheusOperator.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.telemetry.prometheusOperator.serviceMonitor.scrapeTimeout }}
    scheme: {{ include "vault.scheme" . | lower }}
    path: /v1/sys/metrics
    params:
      format:
      - prometheus
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{ end }}
