{{/*
Copyright IBM Corp. 2018, 2025
SPDX-License-Identifier: MPL-2.0
*/}}

{{- template "vault.proxyEnabled" . -}}
{{- if .proxyEnabled -}}
{{- if .Values.proxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "proxy.serviceAccount.name" . }}
  namespace: {{ include "vault.namespace" . }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if  .Values.proxy.serviceAccount.extraLabels -}}
      {{- toYaml .Values.proxy.serviceAccount.extraLabels | nindent 4 -}}
    {{- end -}}
  {{ template "proxy.serviceAccount.annotations" . }}
{{- end }}
{{- end }}
