{{- $route := .Values.server.route -}}
{{- if .Values.global.openshift }}
{{- if ne .mode "external" }}
{{- if $route.enabled -}}
{{- $serviceName := include "vault.fullname" . -}}
{{- if and (eq .mode "ha" ) (eq (.Values.server.route.activeService | toString) "true") }}
{{- $serviceName = printf "%s-%s" $serviceName "active" -}}
{{- end }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ template "vault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with $route.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- template "vault.route.annotations" . }}
spec:
{{- if $route.host }}
  host: {{ $route.host }}
{{- end }}
  to:
    kind: Service
    name: {{ $serviceName }}
    weight: 100
  port:
    targetPort: 8200
  {{- if $route.tls.enabled }}
  tls:
    insecureEdgeTerminationPolicy: {{ $route.tls.insecureEdgeTerminationPolicy }}
    termination: {{ $route.tls.termination }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

