{{ template "vault.mode" . }}
{{- if and (eq (.Values.global.enabled | toString) "true") (ne .mode "dev") -}}
{{ if or (ne .Values.server.standalone.config "")  (ne .Values.server.ha.config "") -}}
{{- if and (eq (.Values.global.tls.enabled | toString) "true") (eq (.Values.global.tls.generateCustomCerts.enabled | toString) "true") (eq (.Values.global.tls.certString | toString) "-") (eq (.Values.global.tls.keyString | toString) "-") (ne (.Values.global.tls.nameTlsSecret | toString) "-") -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vault.fullname" . }}-preinstall
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "100"
spec:
  activeDeadlineSeconds: {{.Values.global.tls.generateCustomCerts.jobDeadline}}
  template:
    metadata:
      name: {{ template "vault.fullname" . }}-preinstall
      labels:
        helm.sh/chart: {{ include "vault.chart" . }}
        app.kubernetes.io/name: {{ include "vault.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ template "vault.fullname" . }}-preinstall-job
        image: "{{.Values.global.tls.generateCustomCerts.misc.omgwtfssl.image}}:{{.Values.global.tls.generateCustomCerts.misc.omgwtfssl.imageTag}}"
        imagePullPolicy: "Always"
        env:
          - name: CA_EXPIRE
            value: "60"
          - name: SSL_EXPIRE
            value: "60"
          - name: SSL_IP
            value: "127.0.0.1"
          - name: SSL_SUBJECT
            value: "{{.Values.global.tls.generateCustomCerts.certParams.serverName}}"
          - name: SSL_DNS
            value: "{{.Values.global.tls.generateCustomCerts.certParams.alternateServerNames}},{{- .Release.Name -}}.{{- .Release.Namespace -}}.svc.cluster.local"
          - name: SILENT
            value: "true"
          - name: K8S_SECRET_NAME
            value: "{{ .Values.global.tls.nameTlsSecret }}"
          - name: K8S_SECRET_SEPARATE_CA
            value: "true"
          - name: K8S_SECRET_LABELS
            value: "helm.sh/chart= {{ include "vault.chart" . }} app.kubernetes.io/name= {{ include "vault.name" . }} app.kubernetes.io/instance= {{ .Release.Name }} app.kubernetes.io/managed-by= {{ .Release.Service }}"
{{- end }}
{{- end }}
{{- end }}
