# If the repository is public, be sure to change to GitHub hosted runners
name: Lint GitHub Actions Workflows
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/vault-workflows-common/.github/workflows/actionlint.yaml@main
