# If the repository is public, be sure to change to GitHub hosted runners
name: Lint GitHub Actions Workflows
on:
  push:
    paths:
      - .github/workflows/**.yml
  pull_request:
    paths:
      - .github/workflows/**.yml
permissions:
  contents: read
jobs:
  actionlint:
    uses: hashicorp/vault-workflows-common/.github/workflows/actionlint.yaml@main
