name: Unit Tests

on: [push, workflow_dispatch, workflow_call]

jobs:
  bats-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-test-tools
      - uses: actions/checkout@v2
      - run: bats ./test/unit -t
