name: Unit Tests

on: [push, workflow_dispatch, workflow_call]

jobs:
  setup-test-tools:
    uses: ./.github/workflows/setup-test-tools.yaml

  bats-unit-tests:
    needs: setup-test-tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bats ./test/unit -t
